### ISSUE TITLE
Criar exemplo com botão na TableView

### ISSUE THREAD

**Issue by Gabriel200XX** [leandersonandre/ExemplosJavaFX#6]
Olá, necessito dessa ajuda.
Quando fizer, mande-me um email: gabriel20053@gmail.com.

**Comment by leandersonandre** [comment]
Adicionado exemplo https://github.com/leandersonandre/ExemplosJavaFX/tree/master/src/br/com/leandersonandre/javafx/exemplos/layout/tableviewcombotao
