### ISSUE TITLE
Como criar telas dinâmicas

### ISSUE THREAD

**Issue by AndreLuis117** [leandersonandre/ExemplosJavaFX#7]
Como criar telas dinâmicas que se ajustam a resolução do computador e ao tamanho da janela?

**Comment by leandersonandre** [comment]
Oi @AndreLuis117 , criei um exemplo de ajuste automático de tamanho de tela,
de uma olhada.
[Clique aqui.](https://github.com/leandersonandre/ExemplosJavaFX/tree/master/src/br/com/leandersonandre/javafx/exemplos/layout/ajustelayoutautomatico)


Abs!
