### ISSUE TITLE
Criar exemplo de como quebrar linhas do texto no label

### ISSUE THREAD

**Issue by AndreLuis117** [leandersonandre/ExemplosJavaFX#8]
Favor criar um exemplo de como quebrar o texto do label

**Comment by leandersonandre** [comment]
OI @AndreLuis117 , vc precisa adicionar o seguinte atributo no label 

> wrapText="true"

Quando o texto do label for maior que o espaço disponível, irá quebrar linha automaticamente.

![image](https://user-images.githubusercontent.com/16268923/45900646-bac57380-bdb6-11e8-8bdb-7f8a813c97e8.png)
