### ISSUE TITLE
Como arredondar as bordas do objetos?

### ISSUE THREAD

**Issue by AndreLuis117** [leandersonandre/ExemplosJavaFX#9]
É possível arredondar ao borda de qualquer objeto em javaFx? Ou em apenas em alguns componentes específicos?

Se possível criar alguns exemplos

**Comment by leandersonandre** [comment]
OI @AndreLuis117 , vc precisa adicionar o seguinte css no componente que deseja arrendondar.

> style="-fx-background-radius: 10;"

Resultado esperado:

![image](https://user-images.githubusercontent.com/16268923/45900865-62db3c80-bdb7-11e8-8c75-ba656b7f9e3b.png)
